### PR TITLE
Replace manual arguments parser with argparse module

### LINKED ISSUE #11: Add command line options.

### PR DESCRIPTION
**Pull request by revolter**
Closes #11.

### CODE REVIEW

**Comment by xp4xbox** [comment]
I am not very familiar with argparse. But could you change it, so the argument could be ```--open <text file path>```.

**Comment by revolter** [comment]
I did it like that because previously, you would simply pass the file path, so I didn't want to change the behavior, but if you do want, sure, no problem.

Also, do you need descriptions for it? So if you run `python2.7 Puffader.py -h` or `python2.7 Puffader.py --help`, you would see this:

```bash
usage: Puffader.py [-h] [-o OPEN]

Test script description.

optional arguments:
  -h, --help            show this help message and exit
  -o OPEN, --open OPEN  test argument description
```

Is it ok if you can also pass `-o <text file path>`?

**Comment by xp4xbox** [comment]
Yes, that would be very useful especially for future expansion.

**Comment by revolter** [comment]
Could you formulate the script and `open` argument descriptions?

**Comment by revolter** [comment]
The script description could be taken from the README:

> Puffader is an opensource, hidden and undetectable keylogger for windows written in Python 2.7. Puffader can easily be configured to send messages over ftp or email as well be configured for specific times to send logs, etc.

And the argument description could be something along the lines of:

> the path to the file to open in Notepad

**Comment by xp4xbox** [comment]
I have already incorporated a few more features in this program, which would require a description change when I push the commit once this pr is merged. So I would like the description to be blank for now. 

I would like the description for -o to be ```path to text file to open in notepad```.

I would also like a -s --startup, for making the program start at startup and -r --remove for stopping the program from running at startup.

**Comment by revolter** [comment]
Done. Let me know if it's ok.

**Comment by xp4xbox** [comment]
Looks good, can you squash your commits.

**Comment by revolter** [comment]
I'll leave them as they are instead of rebasing them. You can easily squash them yourself just before merging the PR right from the browser by clicking the down arrow next to the green `Merge pull request` button and choosing the `Squash and merge` option. Let me know if you have any problems with it.

**Comment by xp4xbox** [comment]
That's easy, I've always used the command line for that. I never knew that. Thanks!

**Comment by revolter** [comment]
I think it also gives you commands to accomplish this, but I'm not sure. Or it did before adding the easier intuitive drop-down menu. Thanks for merging, glad I could help 😄

**Comment by xp4xbox** [comment]
Could you take a look at #20? @revolter

**Comment by xp4xbox** [comment]
For some reason arg parse isnt working for me. Whenever I pass -o and the text file, it just skips the entire if statment.

**Pull request merged**
