### PR TITLE
cx_Freeze basic instructions

### PR DESCRIPTION
**Pull request by modelorona**
Please excuse the branch merge on my part, that was a misclick. Let me know if you would like more.

### CODE REVIEW

**Comment by xp4xbox** [comment]
I was hoping for a setup file for cx_freeze such as I did for py2exe https://github.com/xp4xbox/Puffader/blob/master/setup.py. In order for cx_Freeze to include and exclude specific modules.  As well for the program to run in windowed mode if possible.

**Comment by modelorona** [comment]
Ah right fair enough. Let me take a look into that. Do you have a preference for the setup file name? Something like cx_freeze_setup.py?

Edit:
Perhaps a command flag such as `-cx` or `-px` would serve better better than 2 separate setup files.

**Comment by xp4xbox** [comment]
I would like to have two seperate files if possible to make it easier. cx_freeze_setup.py is good.

**Comment by modelorona** [comment]
Thoughts?

As for the windowed mode, could you elaborate a bit more on what you mean?

**Comment by xp4xbox** [comment]
Looks good. I did some testing and everything seemed to work fine. For the windowed mode, I meant so that the program would run without any console showing up as you did.

One thing I would prefer before the pr gets merged, is that cx_freeze creates many many folders when it compiles the .exe. With many modules never even used. Would it be possible for you to clean it up?

**Comment by modelorona** [comment]
Just the folders or everything besides the exe? Isn't the exe using those or are they leftovers?

**Comment by xp4xbox** [comment]
The exe needs some of thoses folders to be in the same directory in order to run. As well all the other files.

**Comment by modelorona** [comment]
I've been hunting around forums and documentation and haven't been able to find a flag or similar which would package only the modules that are used, and according to [this](https://stackoverflow.com/questions/27281317/cx-freeze-preventing-including-unneeded-packages?noredirect=1&lq=1) cx_freeze takes all of the modules you have on your machine.

**Comment by xp4xbox** [comment]
What about excluding all default python modules not used? That would help cut down on size.

**Comment by xp4xbox** [comment]
I'll see if I can find all unused modules.

**Comment by modelorona** [comment]
Sorry I've not been able to take a look at it today. Yesterday I wasn't able to find any way to NOT include all the unused modules easily

**Comment by xp4xbox** [comment]
I did some testing and I found theses modules can be excluded:

xml, pymsgbox, logging, pyscreeze, pytweening, test, distutils, PIL, unittest, importlib, reprlib, future, builtins, _dummy_thread

Overall it cuts down about 40% of the size.

**Comment by xp4xbox** [comment]
After even more testing, I found out that its best just to include all modules.

**Comment by modelorona** [comment]
Why is it better to include all modules? Out of curiosity

**Comment by xp4xbox** [comment]
Since on different systems in order to ensure the program runs 100% right its best to include all modules.

**Pull request merged**
